#!/usr/bin/env python3
"""Build atlas/data/places.js: places of the Deccan and Basalt collections, normalised and merged.
Only ids are stored per place; titles and dates are read from the collections' own entries.js at load.
The spelling rules live in tools/places.py, shared with the text edition's by-place index.
Run: python3 tools/atlas_places.py"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))                       # the site repository
OUT = os.path.join(ROOT, "atlas", "data", "places.js")

from data import load
from places import Places, REGION, key_of

deccan = load("deccan/data/entries.js")
basalt = load("basalt-and-laterite/data/entries.js")
P = Places(deccan + basalt)

places = {}
def add(e, coll):
    p = e.get("place")
    if not p:
        return
    name, state, locality = P.canon(p)
    kind = "region" if name in REGION else "place"
    key = key_of(name)
    rec = places.setdefault(key, {"key": key, "name": name, "state": state, "kind": kind,
                                  "aliases": [], "lat": [], "lon": [], "deccan": [], "basalt": []})
    if not rec["state"] and state:
        rec["state"] = state
    if p not in rec["aliases"]:
        rec["aliases"].append(p)
    if e.get("lat") is not None:
        rec["lat"].append(e["lat"]); rec["lon"].append(e["lon"])
    rec[coll].append(e["id"])

for e in deccan:
    add(e, "deccan")
for e in basalt:
    add(e, "basalt")

out = []
for rec in places.values():
    la, lo = rec.pop("lat"), rec.pop("lon")
    rec["lat"] = round(sum(la) / len(la), 3) if la else None
    rec["lon"] = round(sum(lo) / len(lo), 3) if lo else None
    rec["spread"] = round(max(max(la) - min(la), max(lo) - min(lo)), 3) if len(la) > 1 else 0
    out.append(rec)
out.sort(key=lambda r: (r["kind"] != "place", r["name"].lower()))

for r in out:
    if r["spread"] > 0.05 or len(r["aliases"]) > 1:
        print(f'{r["name"]:34} {r["state"]:16} spread={r["spread"]:<6} {r["aliases"]}')
print(len(out), "places;", sum(len(r["deccan"]) for r in out), "deccan refs;", sum(len(r["basalt"]) for r in out), "basalt refs")
both = [r["name"] for r in out if r["deccan"] and r["basalt"]]
print("in both collections:", both)

js = ("/* places.js – the places of the Deccan and Basalt & Laterite collections, normalised from each entry's\n"
      "   `place` field ('X, State' -> X; spelling variants merged; localities folded into their city; the state kept).\n"
      "   Only entry ids are stored here; titles, dates and each entry's own place label come from the collections' data files at load.\n"
      "   Generated by tools/atlas_places.py over deccan/data/entries.js and basalt-and-laterite/data/entries.js; regenerate rather than edit. */\n"
      "window.ATLAS_PLACES = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
open(OUT, "w", encoding="utf-8").write(js)
print("wrote", OUT, len(js.encode()), "bytes")
